// Mock data for RCS Team Inbox

export const mockChats = [
  {
    id: "1",
    customerName: "Sarah Johnson",
    customerPhone: "+1 555-0123",
    customerEmail: "sarah.johnson@email.com",
    customerAvatar: "",
    platform: "rcs",
    status: "open",
    assignedTo: "John Smith",
    assignedAt: new Date(Date.now() - 3600000),
    lastMessage: "Hi, I need help with my order",
    lastMessageTime: "2 min ago",
    unreadCount: 3,
    tags: ["vip", "order-issue"],
    notes: "VIP customer - handle with priority. Previous order: #12345",
    isBookmarked: true,
    isActive24h: true,
    priority: "urgent",
    createdAt: new Date(Date.now() - 7200000),
    updatedAt: new Date(Date.now() - 120000),
    lastActivity: new Date(Date.now() - 120000),
    customerDetails: {
      country: "United States",
      timezone: "EST",
      language: "English",
    },
    source: "web",
    totalMessages: 15,
    agentResponseTime: 45,
    messages: [
      {
        id: "m1",
        content: "Hello! How can I help you today?",
        type: "text",
        timestamp: "10:30 AM",
        sender: "agent",
        status: "read",
        messageTime: new Date(Date.now() - 3600000),
        isTemplate: true,
      },
      {
        id: "m2",
        content: "Hi, I need help with my order",
        type: "text",
        timestamp: "10:32 AM",
        sender: "customer",
        status: "delivered",
        messageTime: new Date(Date.now() - 120000),
      },
    ],
  },
  {
    id: "2",
    customerName: "Mike Chen",
    customerPhone: "+1 555-0124",
    customerEmail: "mike.chen@email.com",
    platform: "rcs",
    status: "pending",
    lastMessage: "When will my package arrive?",
    lastMessageTime: "5 min ago",
    unreadCount: 1,
    tags: ["shipping", "follow-up"],
    notes: "Customer waiting for shipping update",
    isBookmarked: false,
    isActive24h: true,
    priority: "medium",
    createdAt: new Date(Date.now() - 10800000),
    updatedAt: new Date(Date.now() - 300000),
    lastActivity: new Date(Date.now() - 300000),
    customerDetails: {
      country: "Canada",
      timezone: "PST",
      language: "English",
    },
    source: "mobile",
    totalMessages: 8,
    agentResponseTime: 120,
    messages: [],
  },
  {
    id: "3",
    customerName: "Emily Rodriguez",
    customerPhone: "+1 555-0125",
    customerEmail: "emily.rodriguez@email.com",
    platform: "rcs",
    status: "resolved",
    assignedTo: "Alice Johnson",
    assignedAt: new Date(Date.now() - 7200000),
    lastMessage: "Thank you for your help!",
    lastMessageTime: "1 hour ago",
    unreadCount: 0,
    tags: ["resolved", "satisfied"],
    notes: "Issue resolved - customer satisfied with resolution",
    isBookmarked: false,
    isActive24h: false,
    priority: "low",
    createdAt: new Date(Date.now() - 14400000),
    updatedAt: new Date(Date.now() - 3600000),
    lastActivity: new Date(Date.now() - 3600000),
    customerDetails: {
      country: "Mexico",
      timezone: "CST",
      language: "Spanish",
    },
    source: "api",
    totalMessages: 12,
    agentResponseTime: 30,
    messages: [],
  },
  {
    id: "4",
    customerName: "David Kim",
    customerPhone: "+1 555-0126",
    customerEmail: "david.kim@email.com",
    platform: "rcs",
    status: "open",
    lastMessage: "Need technical support",
    lastMessageTime: "10 min ago",
    unreadCount: 2,
    tags: ["technical", "urgent"],
    notes: "Technical issue with product installation",
    isBookmarked: true,
    isActive24h: true,
    priority: "high",
    createdAt: new Date(Date.now() - 1800000),
    updatedAt: new Date(Date.now() - 600000),
    lastActivity: new Date(Date.now() - 600000),
    customerDetails: {
      country: "South Korea",
      timezone: "KST",
      language: "Korean",
    },
    source: "web",
    totalMessages: 5,
    messages: [],
  },
  {
    id: "5",
    customerName: "Anna Mueller",
    customerPhone: "+49 555-0127",
    customerEmail: "anna.mueller@email.com",
    platform: "rcs",
    status: "closed",
    assignedTo: "Bob Wilson",
    assignedAt: new Date(Date.now() - 86400000),
    lastMessage: "Issue resolved, thanks!",
    lastMessageTime: "1 day ago",
    unreadCount: 0,
    tags: ["closed", "satisfied"],
    notes: "Customer confirmed issue resolution",
    isBookmarked: false,
    isActive24h: false,
    priority: "low",
    createdAt: new Date(Date.now() - 172800000),
    updatedAt: new Date(Date.now() - 86400000),
    lastActivity: new Date(Date.now() - 86400000),
    customerDetails: {
      country: "Germany",
      timezone: "CET",
      language: "German",
    },
    source: "import",
    totalMessages: 20,
    agentResponseTime: 15,
    messages: [],
  },
];

export const mockTemplates = [
  {
    id: "t1",
    name: "Welcome Message",
    content:
      "Hello {{name}}! Welcome to our RCS messaging service. How can we assist you today?",
    category: "greeting",
    variables: ["name"],
  },
  {
    id: "t2",
    name: "Order Status",
    content:
      "Hi {{name}}, your order {{orderNumber}} is currently {{status}}. Expected delivery: {{deliveryDate}}",
    category: "support",
    variables: ["name", "orderNumber", "status", "deliveryDate"],
  },
  {
    id: "t3",
    name: "Thank You",
    content:
      "Thank you for contacting us, {{name}}! We appreciate your business and are here to help.",
    category: "general",
    variables: ["name"],
  },
  {
    id: "t4",
    name: "Follow Up",
    content:
      "Hi {{name}}, just following up on your inquiry about {{topic}}. Do you need any additional assistance?",
    category: "support",
    variables: ["name", "topic"],
  },
];

export const quickResponses = [
  {
    id: "q1",
    name: "Thank you",
    content: "Thank you for contacting us!",
    shortcut: "/thanks",
  },
  {
    id: "q2",
    name: "Please wait",
    content: "Please give me a moment to check this for you.",
    shortcut: "/wait",
  },
  {
    id: "q3",
    name: "Escalate",
    content:
      "I'm escalating this to our specialist team for better assistance.",
    shortcut: "/escalate",
  },
  {
    id: "q4",
    name: "Follow up",
    content: "I'll follow up with you shortly with more information.",
    shortcut: "/followup",
  },
  {
    id: "q5",
    name: "Resolved",
    content:
      "Great! I'm glad we could resolve your issue. Is there anything else I can help you with?",
    shortcut: "/resolved",
  },
];

export const mockWebhooks = [
  {
    id: "wh1",
    name: "RCS Message Webhook",
    url: "https://your-panel.com/webhooks/rcs",
    type: "rcs",
    isActive: true,
    secret: "wh_secret_123",
    events: ["message.received", "message.delivered", "message.read"],
    createdAt: new Date(Date.now() - 86400000),
    lastTriggered: new Date(Date.now() - 300000),
  },
  {
    id: "wh2",
    name: "Chat Status Updates",
    url: "https://your-panel.com/webhooks/status",
    type: "general",
    isActive: true,
    events: ["chat.created", "chat.updated"],
    createdAt: new Date(Date.now() - 172800000),
    lastTriggered: new Date(Date.now() - 3600000),
  },
];

export const mockWebhookResponses = [
  {
    id: "wr1",
    webhookId: "wh1",
    timestamp: new Date(Date.now() - 300000),
    status: "success",
    statusCode: 200,
    responseTime: 145,
    payload: {
      event: "message.received",
      chat_id: "1",
      from: "+1 555-0123",
      message: "Hi, I need help with my order",
      timestamp: new Date().toISOString(),
    },
    response: { success: true, message: "Webhook processed successfully" },
  },
  {
    id: "wr2",
    webhookId: "wh1",
    timestamp: new Date(Date.now() - 600000),
    status: "error",
    statusCode: 500,
    responseTime: 5000,
    payload: {
      event: "message.delivered",
      chat_id: "2",
      message_id: "msg123",
    },
    error: "Internal server error",
  },
  {
    id: "wr3",
    webhookId: "wh2",
    timestamp: new Date(Date.now() - 900000),
    status: "success",
    statusCode: 200,
    responseTime: 98,
    payload: {
      event: "chat.created",
      chat_id: "4",
      customer_phone: "+1 555-0126",
      platform: "rcs",
    },
    response: { success: true, chat_stored: true },
  },
];
